class TaskModel {
  final String id; //the id will generated using UUID
  final String
      notificationId; //the id will be generated by DateTime.now().millisecondsSinceEpoch.remainder(100000) or by the dataBase
  final String title;
  final String details;
  final String category;
  final String isDone;
  final String time;
  final String date;
  bool isSelected =
      false; //used in selection of tasks, that value is not stored in the database

  TaskModel({
    required this.id,
    required this.title,
    this.notificationId = '',
    this.details = '',
    this.category = '',
    this.isDone = 'false',
    this.time = '',
    this.date = '',
  });

  factory TaskModel.fromMap(Map<String, dynamic> map) {
    return new TaskModel(
      id: map['id'] as String,
      notificationId: map['notificationId'] as String,
      title: map['title'] as String,
      details: map['details'] as String,
      category: map['category'] as String,
      isDone: map['isDone'] as String,
      time: map['time'] as String,
      date: map['date'] as String,
    );
  }

  Map<String, dynamic> toMap() {
    // ignore: unnecessary_cast
    return {
      'id': this.id,
      'notificationId': this.notificationId,
      'title': this.title,
      'details': this.details,
      'category': this.category,
      'isDone': this.isDone,
      'time': this.time,
      'date': this.date,
    } as Map<String, dynamic>;
  }
}
